"""Streamlit live demo and saved-run viewer. Runs the CLI, never imports the engine.

uv run --extra dashboard streamlit run src/conflict_sim/dashboard.py
"""

import html
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from uuid import uuid4

import pandas as pd
import streamlit as st
from hydra import compose, initialize_config_dir

CONF_DIR = Path(__file__).resolve().parents[2] / "conf"

LIST_COLUMNS = [
    "run",
    "created_at",
    "rule",
    "agents",
    "seed",
    "backend",
    "model",
    "utterances",
    "ticks",
    "stop_reason",
]


def discover_runs(root: Path) -> tuple[list[dict], list[str]]:
    """Find every corpus under root, newest first, plus the names of unreadable ones."""
    rows: list[dict] = []
    broken: list[str] = []
    for meta_path in sorted(root.rglob("corpus/run.json")):
        directory = meta_path.parent.parent
        name = str(directory.relative_to(root))
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            broken.append(name)
            continue
        config = meta.get("config", {})
        rows.append(
            {
                "run": name,
                "created_at": meta.get("created_at", ""),
                "rule": config.get("rule"),
                "agents": config.get("n_agents"),
                "seed": config.get("random_seed"),
                "backend": config.get("backend"),
                "model": config.get("model_speak"),
                "utterances": meta.get("generated_utterances"),
                "ticks": meta.get("ticks"),
                "stop_reason": meta.get("stop_reason"),
                "corpus": str(meta_path.parent),
            }
        )
    rows.sort(key=lambda row: row["created_at"], reverse=True)
    return rows, broken


def _read_jsonl(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    lines = path.read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


def load_run(corpus: Path) -> dict:
    return {
        "meta": json.loads((corpus / "run.json").read_text(encoding="utf-8")),
        "utterances": _read_jsonl(corpus / "utterances.jsonl"),
        "decisions": _read_jsonl(corpus / "decisions.jsonl"),
    }


def reply_depth(utterances: list[dict]) -> dict[str, int]:
    """Depth of each utterance in the reply tree. Dangling and cyclic parents stop the walk."""
    parents = {u["id"]: u["reply-to"] for u in utterances}
    depths: dict[str, int] = {}
    for utterance_id in parents:
        depth = 0
        seen = {utterance_id}
        current = parents[utterance_id]
        while current is not None and current not in seen:
            depth += 1
            seen.add(current)
            if current not in parents:
                break
            current = parents[current]
        depths[utterance_id] = depth
    return depths


# Deep threads stop indenting here, the way {{outdent}} is used on a real talk page.
# A bare string here would be a module-level expression, which Streamlit magic renders.
MAX_INDENT = 6

TALK_PAGE_CSS = """
<style>
.talk {
  background: #ffffff;
  color: #202122;
  font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.6;
  padding: 1.5em 1.75em 2em;
  border: 1px solid #a2a9b1;
  box-sizing: border-box;
  width: 100%;
}
.talk .ombox {
  border: 1px solid #a2a9b1;
  border-left: 10px solid #36c;
  background: #f8f9fa;
  padding: 0.6em 0.9em;
  margin-bottom: 1.6em;
  font-size: 13px;
  color: #54595d;
}
.talk h2 {
  font-family: "Linux Libertine", Georgia, "Times New Roman", serif;
  font-size: 1.5em;
  font-weight: normal;
  color: #000;
  border-bottom: 1px solid #a2a9b1;
  padding-bottom: 0.25em;
  margin: 0 0 0.35em;
}
.talk .pagemeta { color: #54595d; font-size: 13px; margin: 0 0 1.8em; }
.talk .comment { margin: 0 0 1.1em; padding-left: 0.9em; }
.talk .comment[data-depth="0"] { padding-left: 0; }
.talk .comment[data-depth]:not([data-depth="0"]) { border-left: 1px solid #eaecf0; }
.talk .comment p { margin: 0 0 0.6em; }
.talk .sig { color: #54595d; font-size: 13px; }
.talk .user { color: #3366cc; }
.talk .outdent { color: #72777d; }
.talk .tag {
  background: #eaecf0;
  color: #54595d;
  font-size: 11px;
  padding: 0 0.4em;
  margin-left: 0.3em;
}
</style>
"""


def talk_page_html(utterances: list[dict], title: str, subtitle: str) -> str:
    """Render the thread the way a MediaWiki talk page reads: colon indents and signatures."""
    depths = reply_depth(utterances)
    parts = [
        TALK_PAGE_CSS,
        '<div class="talk">',
        '<div class="ombox">Synthetic run generated by conflict-sim. '
        "Not Wikipedia content and not evidence about real editor behavior.</div>",
        f"<h2>{html.escape(title)}</h2>",
        f'<p class="pagemeta">{html.escape(subtitle)}</p>',
    ]
    for utterance in utterances:
        depth = depths.get(utterance["id"], 0)
        indent = min(depth, MAX_INDENT) * 1.6
        body = "".join(
            f"<p>{html.escape(block.strip())}</p>"
            for block in re.split(r"\n\s*\n", utterance["text"])
            if block.strip()
        )
        seed = utterance["timestamp"] == 0
        when = '<span class="tag">seed</span>' if seed else f"tick {utterance['timestamp']}"
        if depth > MAX_INDENT:
            when += f' · <span class="outdent">outdented from depth {depth}</span>'
        parts.append(
            f'<div class="comment" data-depth="{depth}" '
            f'style="margin-left:{indent:g}em" title="{html.escape(utterance["id"])}">'
            f"{body}"
            f'<div class="sig">— <span class="user">{html.escape(utterance["speaker"])}'
            f"</span> · {when}</div>"
            "</div>"
        )
    parts.append("</div>")
    return "\n".join(parts)


@st.cache_data(show_spinner=False)
def _cached_runs(root: str, _stamp: float) -> tuple[list[dict], list[str]]:
    return discover_runs(Path(root))


@st.cache_data(show_spinner=False)
def _cached_run(corpus: str, _stamp: float) -> dict:
    return load_run(Path(corpus))


def _stamp_of(path: Path) -> float:
    return path.stat().st_mtime if path.exists() else 0.0


def start_live(root: Path, overrides: list[str]) -> tuple[subprocess.Popen, Path]:
    directory = root.resolve() / "live" / f"{datetime.now():%Y%m%d-%H%M%S}-{uuid4().hex[:8]}"
    directory.mkdir(parents=True, exist_ok=False)
    with (directory / "console.log").open("w", encoding="utf-8") as log:
        process = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "conflict_sim.cli",
                "live=true",
                f"hydra.run.dir={json.dumps(str(directory))}",
                *overrides,
            ],
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    return process, directory


def stop_live(process: subprocess.Popen, directory: Path) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=3)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=3)
    path = directory / "live.json"
    progress = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    if progress.get("status") == "completed":
        return
    progress.update(status="stopped", message="Stopped by you · partial conversation retained")
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(progress, ensure_ascii=False), encoding="utf-8")
    temporary.replace(path)


def live_progress() -> None:
    process = st.session_state.get("live_process")
    if process is None:
        st.info("Choose a mode and press Start simulation.")
        return
    if process.poll() is not None and st.session_state.get("live_busy"):
        st.session_state.live_busy = False
        st.cache_data.clear()
        st.rerun()

    directory = st.session_state.live_directory
    path = directory / "live.json"
    progress = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    status = progress.get("status", "starting")
    message = progress.get("message", "Starting simulation…")
    if process.poll() is not None and status not in {"completed", "failed", "stopped"}:
        status, message = "failed", "The process exited before saving a result. See console.log."
    if status == "failed":
        st.error(message)
    elif status == "stopped":
        st.warning(message)
    elif status == "completed":
        st.success(message)
    else:
        st.info(message)
    st.caption(f"Run: {directory}")
    config = progress.get("config", {})
    ticks = progress.get("ticks", 0)
    maximum = config.get("max_ticks", 1)
    utterances = progress.get("utterances", [])
    decisions = progress.get("decisions", [])
    columns = st.columns(3)
    columns[0].metric("Generated comments", max(0, len(utterances) - 2))
    columns[1].metric("Completed ticks", f"{ticks} / {maximum}")
    columns[2].metric("Status", status.capitalize())
    st.progress(min(ticks / maximum, 1.0))

    transcript, reflections = st.columns([3, 2])
    with transcript:
        st.subheader("Public conversation")
        if utterances:
            with st.container(height=500, autoscroll=True):
                st.html(talk_page_html(utterances, "Article discussion", config.get("rule", "")))
    with reflections:
        st.subheader("Agent reflections")
        st.caption("Private self-reports · visible here, never shared with other agents")
        latest = {event["agent"]: event for event in decisions if event.get("reflection")}
        with st.container(height=500):
            for agent in config.get("agents", []):
                event = latest.get(agent["name"])
                with st.expander(agent["name"], expanded=True):
                    if event is None:
                        st.caption("Waiting for a first reflection")
                        continue
                    st.caption(
                        f"Tick {event['tick']} · urge {event['urge']:.2f} · "
                        f"{'Posted' if event['posted'] else 'Not posted'}"
                    )
                    st.text(event["reflection"])
                    if event.get("decision_source") == "retry":
                        st.caption(f"Reused from tick {event['decision_tick']}")
    if decisions:
        with st.expander("Decision log"):
            st.dataframe(pd.DataFrame(decisions), width="stretch", hide_index=True)


def live_view(root: Path) -> None:
    # Commit submitted values before disabling the form on the next rerun.
    for key, value in st.session_state.pop("live_form_values", {}).items():
        st.session_state[key] = value
    with initialize_config_dir(version_base="1.3", config_dir=str(CONF_DIR)):
        defaults = compose(config_name="config")
    process = st.session_state.get("live_process")
    running = process is not None and process.poll() is None
    with st.expander("Simulation settings", expanded=process is None), st.form("live_settings"):
        columns = st.columns(3)
        backend = columns[0].selectbox(
            "Backend",
            ["demo", "openai"],
            index=["demo", "openai"].index(defaults.backend),
            disabled=running,
            key="live_backend",
        )
        rules = ["round_robin", "random", "bidding", "event_driven"]
        rule = columns[1].selectbox(
            "Order rule", rules, index=rules.index(defaults.rule), disabled=running, key="live_rule"
        )
        modes = ["none", "summary", "full"]
        memory = columns[2].selectbox(
            "Memory",
            modes,
            index=modes.index(defaults.memory_mode),
            disabled=running,
            key="live_memory",
        )
        ticks = columns[0].number_input(
            "Max ticks",
            min_value=1,
            value=defaults.max_ticks,
            disabled=running,
            key="live_max_ticks",
        )
        seed = columns[1].number_input(
            "Random seed", value=defaults.random_seed, step=1, disabled=running, key="live_seed"
        )
        st.caption(
            f"{defaults.n_agents} agents · OpenAI model: {defaults.model_speak} · "
            "Personas and other settings follow conf/config.yaml."
        )
        st.caption("demo: scripted, no API calls · openai: live generation using your .env key")
        started = st.form_submit_button("Start simulation", type="primary", disabled=running)
    if started and not running:
        try:
            process, directory = start_live(
                root,
                [
                    f"backend={backend}",
                    f"rule={rule}",
                    f"memory_mode={memory}",
                    f"max_ticks={ticks}",
                    f"random_seed={seed}",
                ],
            )
        except OSError as exc:
            st.error(f"Could not start the simulation: {exc}")
        else:
            st.session_state.update(live_process=process, live_directory=directory, live_busy=True)
            st.session_state.live_form_values = {
                "live_backend": backend,
                "live_rule": rule,
                "live_memory": memory,
                "live_max_ticks": ticks,
                "live_seed": seed,
            }
            st.rerun()
    if st.button("Stop simulation", disabled=not running):
        stop_live(process, st.session_state.live_directory)
        st.session_state.live_busy = False
        st.rerun()
    st.fragment(run_every=0.5 if running else None)(live_progress)()


def main() -> None:
    st.set_page_config(page_title="ConflictDynamics", layout="wide")
    st.title("ConflictDynamics")

    busy = st.session_state.get("live_busy", False)
    page = st.sidebar.radio("View", ["Live simulation", "Saved runs"], disabled=busy)
    root_input = st.sidebar.text_input("runs directory", value="runs", disabled=busy)
    if st.sidebar.button("Reload"):
        st.cache_data.clear()
    root = Path(root_input).expanduser()

    if page == "Live simulation":
        live_view(root)
        return

    rows, broken = _cached_runs(str(root), _stamp_of(root))
    if broken:
        st.warning(f"Skipped {len(broken)} run(s) with an unreadable run.json: {', '.join(broken)}")
    if not rows:
        st.info(f"No corpus found under {root.resolve()}. Run `uv run conflict-sim` first.")
        return

    st.dataframe(pd.DataFrame(rows)[LIST_COLUMNS], width="stretch", hide_index=True)

    names = [row["run"] for row in rows]
    selected = st.selectbox("Run", names)
    row = next(item for item in rows if item["run"] == selected)
    corpus = Path(row["corpus"])
    run = _cached_run(str(corpus), _stamp_of(corpus / "run.json"))

    decisions = run["decisions"]
    urges = [
        event["urge"]
        for event in decisions
        if "urge" in event and event.get("decision_source", "new") == "new"
    ]
    columns = st.columns(4)
    columns[0].metric("Generated", run["meta"].get("generated_utterances"))
    columns[1].metric("Ticks", run["meta"].get("ticks"))
    columns[2].metric("Stopped by", run["meta"].get("stop_reason"))
    columns[3].metric("Mean urge", round(sum(urges) / len(urges), 3) if urges else "—")

    transcript_tab, decisions_tab = st.tabs(["Transcript", "Decisions"])

    with transcript_tab:
        config = run["meta"].get("config", {})
        subtitle = " · ".join(
            str(part)
            for part in (
                config.get("rule"),
                f"{config.get('n_agents')} editors",
                f"seed {config.get('random_seed')}",
                config.get("model_speak") or config.get("backend"),
            )
            if part
        )
        st.html(talk_page_html(run["utterances"], selected, subtitle))

    with decisions_tab:
        if decisions:
            st.dataframe(pd.DataFrame(decisions), width="stretch", hide_index=True)
            reflections = [event for event in decisions if event.get("reflection")]
            if reflections:
                editor = st.selectbox("Agent", sorted({event["agent"] for event in reflections}))
                entries = [event for event in reflections if event["agent"] == editor]
                tick = st.selectbox("Reflection tick", [event["tick"] for event in entries])
                event = next(event for event in entries if event["tick"] == tick)
                origin = event.get("decision_tick", tick)
                status = "Reused" if event.get("decision_source") == "retry" else "New"
                st.caption(f"{status} reflection · originally recorded at tick {origin}")
                st.text(event["reflection"])
            else:
                st.info("This run recorded no reflections.")
        else:
            st.info("This run recorded no decisions.")


if __name__ == "__main__":
    main()
